version: '3'

services:
  #
  # Proxy - HTTP entrypoint
  proxy:
    image: ${COMPOSE_PROJECT_NAME}_proxy:latest
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint
    restart: unless-stopped
    expose:
      - "80"
    build:
      context: ./proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${NGINX_LOGS:-./app_logs/nginx}:/var/log/nginx
      - ${NEXTCLOUD_DATA:-./app_wordpress}:/var/www/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - https-revproxy
      - nextcloud

  #
  # Application & DB
  app:
    image: nextcloud:fpm-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - nextcloud

  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud

volumes:
  db:
  nextcloud:

networks:
  https-revproxy:
    external:
      name: ${APPS_NETWORK}
  nextcloud: